### ISSUE TITLE
ive got error

### ISSUE THREAD

**Issue by kcaBmask** [damiankw/trivia.eggdrop.tcl#1]
Tcl error in file 'tigers.conf':
[23:59:56] can't read "tr(cmd)": no such variable
    while executing
"bind pub - $tr(cmd)trivia pub:trivia"
    (file "trivia/trivia.etcl" line 4)
    invoked from within
"source trivia/trivia.etcl"

I am using eggdrop 1.8.3

**Comment by damiankw** [comment]
In your tigers.conf file (which I assume is your renamed eggdrop.conf?) you need to source trivia/trivia.conf, you also need to edit the trivia.conf so it all relates to your own system :)

**Comment by ghost** [comment]
it works.. but no questions displaying in the channel. how?

**Comment by damiankw** [comment]
> it works.. but no questions displaying in the channel. how?

I actually just booted this back up a couple of days ago and it's been running since then pulling questions fine, so nothing wrong with the script.

Let me see what it's actually doing in the channel?

**Comment by ghost** [comment]
please check.. and update ...  i need this kind of trivia script ..   :) .. i'm using egdgrop 1.9

**Comment by damiankw** [comment]
Yeah.. let me know what it's doing! Show me a log of what it's doing in channel.

**Comment by ghost** [comment]
**FROM THE BOT**
<ALTNICK> [08:48:28] % Loading Trivia Tcl v0.02a...
<ALTNICK> [08:48:28] % Trivia Tcl loaded successfully.


**FROM THE CHANNEL**

<+asL_pLs> !trivia
-ALTNICK- Invalid request: You need to specify a status (on/off).
<+asL_pLs> !trivia on
<ALTNICK> !NOTICE! Trivia is already playing, you can't start it again!



**FROM  trivia.conf**

# user configuration
set tr(cmd) "!";                         # prefix for admin commands in channel
set tr(exclude) "1";                     # list of categories to exclude from trivia, separate by space (according to https://opentdb.com/api_category.php)
set tr(chan) "#nytcrwlrz";                  # channel to run trivia in
set tr(eggdrop) "/home/words/eggdrop/";  # path.to/eggdrop
set tr(script) "scripts";                 # subdirectory under the eggdrop directory where the scripts are
set tr(status) 1;                        # current trivia status, 1=on, 0=off
set tr(answer.delay) 60;                 # delay to wait for answers before revealing the correct one
set tr(game.delay) 60;                   # delay to wait between games

**Comment by ghost** [comment]
by the way..

i got this ..


<asL_pLs> .set errorInfo
<ALTNICK> [08:53:19] #asL_pLs# set errorInfo
<ALTNICK> Currently: can't find package Trf 2.0
<ALTNICK> Currently:     while executing
<ALTNICK> Currently: "package require Trf 2.0"


how to ?

**Comment by damiankw** [comment]
Hey, sorry. I don't know what the Trf error is, that one's got me (I did write this script three years ago though, in one day!).

Wanna give me your network / channel and I'll come have a look?

**Comment by ghost** [comment]
TRF error is ok.. i fix it..

**Comment by jackbolot** [comment]
![Screenshot 2022-11-26 235137](https://user-images.githubusercontent.com/5516141/204100518-42d82e6b-84a3-418a-b6cd-21174bc0a8f7.png)

i make this colour full hehe
i have a question,why when no one answer ,keep saying they have been awarded instead of no one answer the question and go to the next question...i hope u can make new version....

**Comment by damiankw** [comment]
> ![Screenshot 2022-11-26 235137](https://user-images.githubusercontent.com/5516141/204100518-42d82e6b-84a3-418a-b6cd-21174bc0a8f7.png)
> 
> i make this colour full hehe i have a question,why when no one answer ,keep saying they have been awarded instead of no one answer the question and go to the next question...i hope u can make new version....

I've fixed this up, it's pretty easy bug fix :)

**Comment by jackbolot** [comment]
![Screenshot 2022-12-06 151950](https://user-images.githubusercontent.com/5516141/205858049-74b20b12-5995-496b-b7a6-2b3019c1c653.png)

work great..any possible to use indonesia db question sir..coz im indoensian

**Comment by damiankw** [comment]
> 

I'm not so sure about the indonesian questions! I just use opentdb.com to pull questions and that's only English. If you have another source in Indonesian that has a similar API it should be easy enough to adapt.

**Comment by ghost** [comment]
Hi damiankw, is this possible with answers not the letter choices, but the answer itself as like normal trivia?
